<?php
    include("../data/DBConfig.php");
    include_once("../data/sessioncheck.php");

    $yr_ = date("Y");
     $vat = 0;
    if(!isset($_GET['id'])){$database->redirect_to($host);}
    $ticketID = $database->test_input($_GET['id']);
    $ticket = $database->getPurchaseTicket($ticketID);
    if($ticket == null){
        $database->redirect_to($host);
    }
     $sof = $ticket['orderCollect'];
    if($sof == 1){
        $vat = $ticket['vat'];
    }else if(isset($_GET['vat'])){
        $vat= $database->test_input($_GET['vat']);
    }


?>
<div class="modal-header panel-blue">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title">PURCHASE GENERATED BY :<?php echo $database->getMyUserInformation($ticket['adminID'])['fullname'];?></h4>

</div>
  <div class="modal-body">
      <table  style="font-size: 9px" class="table table-striped table-bordered table-advance table-hover">
                <tr>
                    <th class="success"><span contenteditable>Supply #</span></th>
                    <td class="warning"><span contenteditable><?php echo $ticket['ticketNo'];?></span></td>
                     <th class="success"><span contenteditable>Order Collected</span></th>
                    <td class="warning"><span contenteditable><?php echo $ticket['orderCollectedDate'];?></span></td>
                </tr>
                 <tr>
                    <th class="success"><span contenteditable>Account Name</span></th>
                    <td class="warning"><span contenteditable><?php echo $ticket['AccountName'];?></span></td>
                     <th class="success"><span contenteditable>Address</span></th>
                    <td  class="warning"><span contenteditable><?php echo $ticket['Address'].", ".$ticket['areaname'].", ".$ticket["lga"]." L.G.A, ".$ticket['state'];?></span></td>

                </tr>

                <tr >
                    <th class="success"><span contenteditable>Machine Code</span></th>
                    <td class="warning"><span contenteditable><?php echo $ticket['machine_code'];?></span></td>
                     <th class="success"><span contenteditable>Machine Model</span></th>
                    <td class="warning"><span contenteditable><?php echo $ticket['machineBrand'];?></span></td>
                </tr>
                <tr>
                     <th class="success"><span contenteditable>Contract Type</span></th>
                    <td class="warning"><span id="prefix" contenteditable><?php echo $ticket['contract'];?></span></td>
                    <th class="active"><span contenteditable>Status</span></th>
                    <?php $stat = "danger";$stat_="UNPAID";?>
                    <?php if($ticket['orderCollect']==1){$stat = "success";$stat_="PAID";};?>
                    <td class="<?php echo $stat;?>"><span id="prefix" contenteditable><?php echo $stat_;?></span></td>
                </tr>
            </table>
             <hr/>
<table style="font-size: 10px" class="table table-striped table-bordered table-advance table-hover">
                <thead>
                    <tr class="info">
                        <th style="width: 40%">Item</th>
                        <th style="width: 25%">Code</th>
                        <th style="width: 15%">Rate</th>
                        <th style="width: 5%">Qty</th>
                        <th style="width: 20%">Price</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                     $amounted = 0;


                            $salesorder = (array)$database->getPurchaseProductOrderCall($ticket['id']);
                            foreach ($salesorder as $order) {
                    ?>
                    <tr>
                        <td><?php echo $order['productName'];?><?php if($order['ProductType']>1){echo " - ".$order['color'];}?></td>
                        <td><?php echo $order['Code'];?></td>
                        <td> <?php echo $database->convertToMoney($order['Amount']);?></td>
                        <td><?php echo $order['qty'];?></td>
                        <td><?php
                                                $amount_ = $order['qty'] * $order['Amount'];
                                        echo $database->convertToMoney($amount_);?></td>
                    </tr>
                     <?php $amounted += $amount_;}?>

                </tbody>
                <tr>
                       <th colspan="4" style="text-align: right">SUBTOTAL</th>
                        <th style="width: 25%"><?php
                             $sub_total =$amounted;

                             echo  $database->convertToMoney($sub_total);
                        ?></th>
                </tr>
                  <tr>
                       <th colspan="4" style="text-align: right">VAT</th>
                        <th style="width: 25%"> <?php
                        $vatValue = 0;
                             if($vat == 0){$vatValue == 0;}else{$vatValue = 0.05 *$sub_total ;}
                             echo  $database->convertToMoney($vatValue);
                        ?>
                        <?php $added = $sub_total + $vatValue;?></th>
                </tr>
                  <tr>
                       <th colspan="4" style="text-align: right">DISCOUNT <?php echo $ticket['discount'];?>%</th>
                        <th style="width: 25%"> <?php
                                                            $disc = (($ticket['discount']/100) *  $added);
                                                            echo $database->convertToMoney($disc);

                                             ?></th>
                </tr>
                  <tr>
                  <th colspan="2">PURCHASE COLLECTED BY :<?php echo $database->getMyUserInformation($ticket['collectedBy'])['fullname'];?></th>
                       <th colspan="2" style="text-align: right">TOTAL AMOUNT</th>
                        <th style="width: 25%"><?php
                                                            $dis = $added - $disc;
                                                            echo $database->convertToMoney($dis);

                                             ?></th>
                </tr>
                <tr class="success">
                    <th colspan="5">
                        <p style="text-align: center">
                  <b>Amount in words :</b> <?php echo ucwords($database->convert_number_to_words($dis));?> Naira Only
                   </p>
                    </th>
                </tr>
            </table>


      </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Dismiss</button>
        </div>